### ISSUE TITLE
AppImage does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [Tw1ddle/geometrize-installer#1]
This AppImage does not run on Ubuntu 14.04 which is the minimum requirement for inclusion in the [AppImageHub central directory of available AppImages](https://appimage.github.io/apps/).

`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /run/firejail/appimage/.appimage-7254/AppRun)`

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/294509690#L703

This is because geometrize-installer was compiled on a distribution newer than Ubuntu 14.04, or a newer `libstdc++` version was used than what comes with Ubuntu 14.04.

There are (at least) two solutions:
1. Compile on a stock Ubuntu 14.04 (without PPAs that install a newer `libstdc++.so.6`
2. Bundle `libstdc++.so.6` inside the AppImage. In this case make sure to use https://github.com/darealshinji/AppImageKit-checkrt/

Background information:

Some projects require newer C++ standards to build them. To keep the glibc dependency low you can
build a newer GCC version on an older distro and use it to compile the project. This project however will now require a newer version of the `libstdc++.so.6` library than available on that distro. Bundling `libstdc++.so.6` however will in most cases break compatibility with distros that have a newer library version installed into their system than the bundled one. So blindly bundling the library is not reliable. While this is primarily an issue with `libstdc++.so.6` in some rare cases this might also occur with `libgcc_s.so.1`. That's because both libraries are part of GCC. You would have to know the library version of the host system and decide whether to use a bundled library or not before the application is started. This is exactly what the patched AppRun binary from https://github.com/darealshinji/AppImageKit-checkrt/ does. It will search for `usr/optional/libstdc++/libstdc++.so.6` and `usr/optional/libgcc_s/libgcc_s.so.1` inside the AppImage or AppDir. If found it will compare their internal versions with the ones found on the system and prepend their paths to `LD_LIBRARY_PATH` if necessary.

**Comment by probonopd** [comment]
The issue persists.

**Comment by Tw1ddle** [comment]
Thanks for the detailed explanation.

After some trial and error I should have approach (2) working for Linux builds numbered 359 and above. At least, this works on a fresh install of Ubuntu 14.04: https://geometrize-installer-bucket.s3.amazonaws.com/linux/geometrize_359.1_linux_g%2B%2B-8.AppImage

Also the script I'm using: https://github.com/Tw1ddle/geometrize-installer/blob/master/scripts/linux_create_appimage.sh

Please let me know if anything looks wrong. Thanks!
